name: 🚀 Feature Request
description: Suggest a new feature or improvement
title: '[Feature]: '
labels: [enhancement]
body:
  - type: input
    id: shortname
    attributes:
      label: Short Name for Branch
      description: Enter a short, meaningful name (max 15 characters) to help name the feature branch.
      placeholder: e.g., user-dashboard
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Description
      description: What should be added or improved?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternatives you've considered.
